//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prontuario
    {
        public int Id { get; set; }
        public string DescricaoPaciente { get; set; }
        public string Diagnostico { get; set; }
        public string PrescricaoMedicamento { get; set; }
        public string PrescricaoTratamento { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Consulta Consulta { get; set; }
        public virtual Medico Medico { get; set; }
    }
}
